services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"      
    ports:
      - 8081:8081
    networks:
      - mynet
    image: mariamcparland/server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64" 
   ports:
      - 8080:8080
    depends_on:
      - server
    networks:
      - mynet
    image: mariamcparland/client

networks:
  mynet:
